"""add Db relationship for barangay,municilipality and province retain relationship of users

Revision ID: 3a47a955ede5
Revises: 666d5805e378
Create Date: 2025-06-27 17:57:31.350485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a47a955ede5'
down_revision = '666d5805e378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barangay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipality_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_municipality_barangay', 'municipality', ['municipality_id'], ['id'])

    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prov_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_province_municipality', 'province', ['prov_id'], ['id'])
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prov_id')

    with op.batch_alter_table('barangay', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('municipality_id')

    # ### end Alembic commands ###
