"""set relationship of users and department

Revision ID: 509b39185a41
Revises: 3a47a955ede5
Create Date: 2025-07-08 15:18:13.625278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509b39185a41'
down_revision = '3a47a955ede5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=30), nullable=False, server_default='gray'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
