"""add address_1 and address_2 and zipcode to Users

Revision ID: 666d5805e378
Revises: eb7f14c77bfc
Create Date: 2025-06-26 19:09:29.798308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666d5805e378'
down_revision = 'eb7f14c77bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zipcode', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brgy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('munci_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prov_id', sa.Integer(), nullable=True))
        # batch_op.create_foreign_key(None, 'province', ['prov_id'], ['id']) #THIS IS THE INITIAL GENERATION OF ADDITIONAL COLUMN AND TABLE the Fkey_name is not automatically created unlike to mysql xammp that we can input it directly that is why this turns out to "None"
        # batch_op.create_foreign_key(None, 'municipality', ['munci_id'], ['id'])
        # batch_op.create_foreign_key(None, 'barangay', ['brgy_id'], ['id'])
        batch_op.create_foreign_key('fk_users_province', 'province', ['prov_id'], ['id'])
        batch_op.create_foreign_key('fk_users_barangay', 'barangay', ['brgy_id'], ['id'])
        batch_op.create_foreign_key('fk_users_municipality', 'municipality', ['munci_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey') 
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prov_id')
        batch_op.drop_column('munci_id')
        batch_op.drop_column('brgy_id')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('address_2')
        batch_op.drop_column('address_1')

    # ### end Alembic commands ###
